name: "Hello World Python Action"
description: "Prints a custom greeting message using Python"
author: "Lahcen"
inputs:
  name:
    description: "Name to greet"
    required: false
    default: "World"
  greeting:
    description: "Custom greeting"
    required: false
    default: "Hello"
outputs:
  message:
    description: "The full greeting message"
runs:
  using: "python3"
  main: "main.py"
