name: "Hello World Action"
description: "Prints a greeting message"
author: "Lahcen"
inputs:
  name:
    description: "Name to greet"
    required: false
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
runs:
  using: "node16"
  main: "index.js"
