name: Cleanup Old Workflow Runs
on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyJWT cryptography

      - name: Generate JWT Token
        id: generate_jwt
        run: |
          jwt_token = $(python get_jwt_token.py --app_id ${{secrets.APP_ID}} --private_key_path ${{secrets.PRIVATE_KEY_APP}})
          echo "JWT_TOKEN=$jwt_token" >> $GITHUB_ENV

      - name: Get Installation Access Token
        id: get_installation_token
        run: |
          installation_id=$(curl -H "Authorization: Bearer ${{env.JWT_TOKEN}}" \
                               -H "Accept: application/vnd.github.v3+json" \
                               https://api.github.com/app/installations | jq -r '.[0].id')

          access_token=$(curl -X POST \
                        -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/app/installations/${installation_id}/access_tokens | jq -r '.token')

          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Delete Old Workflow Runs
        run: |
          # Fetch old workflow runs
          workflow_runs=$(curl -H "Authorization: token ${{env.ACCESS_TOKEN}}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/${{github.repository}}/actions/runs | jq '.workflow_runs[] | select(.created_at < "'$(date -d '30 days ago' --utc +%Y-%m-%dT%H:%M:%SZ)'") | .id')

          # Loop through and delete each workflow run
          for run_id in $workflow_runs; do
            curl -X DELETE \
              -H "Authorization: token ${{env.ACCESS_TOKEN}}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{github.repository}}/actions/runs/$run_id
          done