name: Test Workflow
on: push

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Publish Test Results
      run: |
        echo "![Company Logo](https://raw.githubusercontent.com/lahcenfahim/demo-git/main/logo.png)" >> $env:GITHUB_STEP_SUMMARY
