name: "Test Python Action"
on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or any version you prefer

      - name: Run custom Python action
        uses: ./hello-action
        with:
          name: "Lahcen"
          greeting: "Hey"
