name: "Test Hello Action"
on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: your-username/hello-action@v2
        with:
          name: "Lahcen"
          greeting: "Hey"
